name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
     
 #     - name: Run tests
  #      run: dotnet test --configuration Release --no-build

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }}


      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.DEPLOYMENT_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourcegroup: rg-ss-test-01
          environment: env-ss-test-01
          name: capp-ss-test-01
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }}