name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Build Docker image
        run: docker build -t artistapi:latest .

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }}

      - name: Run tests
        run: dotnet test --no-build

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy@v2
        with:
          recource-group: rg-ss-test-01
          environment: caenv-brights-2026
          name: capp-ss-test-01
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/artistapi:${{ github.sha }}